import { createSlice } from "@reduxjs/toolkit";

const authSlice = createSlice({
  name: "auth",
  initialState: {
    login: {
      currentUser: null,
      isFetching: false,
      error: false,
      isLogin: false,
      uploadAvt: false,
      
    },
    register: {
      isFetching: false,
      error: false,
      success: false,
    },
    comment: {
      error: false,
      success: false,
    },
    API: {
      BANNER: {
        ALL:"https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/October2022/do-thu-dong-banner-collection2x_60.jpeg",
        WINTER:
          "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/October2022/do-thu-dong-banner-collection2x_60.jpeg",
        TANKTOP:
          "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/AntismellTANKTOP.jpg",
        POLO: "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/AntismellPOLO-2.jpg",
        SHOSE: "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F12%2Fnike-dunk-low-viotech-closer-look-release-information-CT5050-500-00.jpg?w=960&cbr=1&q=90&fit=max",
        PANT: "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/June2022/quan-dai.jpg",
        SHORT:
          "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/June2022/quan-short.jpg",
      },
      ALL:  [
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-den-1.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-den-2.jpg",
          product_name: "Áo thun thể thao dài tay nam Recycle Active - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "199.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-hoodie-daily-wear-1-2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-hoodie-daily-wear-3-2.jpg",
          product_name: "Áo Hoodie nam Daily Wear (mũ trùm có dây rút) - Xanh Navy",
          category_id:"ABC",
          amount:10,
          sell_price: "349.000đ",
          discount: "399.000đ",
          percent: "-13%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-mu-daily-wear-den-6.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-mu-daily-wear-den-5.jpg",
          product_name: "Áo khoác nam có mũ Daily Wear - trượt nước, chống UV 99% - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-for-winter-den-3_29.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-khoac-ni-for-winter-mau-den.jpg",
          product_name: "Áo khoác nỉ nam For Winter (có mũ trùm tiện lợi) - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-den-5_26.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-den-1_78.jpg",
          product_name: "Áo nỉ dài tay Lifewear - thoải mái khi mặc - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "339.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "5",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/modal-ultra-warm-den-1-1.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-giu-nhiet-modal-mau-den.jpg",
          product_name: "Áo giữ nhiệt nam Modal Ultra Warm - mặc là ấm, thoáng khí - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "289.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/_MG_2369-2_(1).jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/NNjac22_46.jpg",
          product_name: "Áo khoác gió thể thao HeiQ ViroBlock, chống UV & trượt nước - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/May2022/DSC04823_copy.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/uvspport_22.jpg",
          product_name: "Áo khoác gió thể thao đa năng cản gió và chống UV - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.7",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/11-181.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/soronanavyu_32.jpg",
          product_name: "Quần nam Daily Pants - sợi Sorona, nhuộm Cleandye - Xanh Navy",
          category_id:"ABC",
          amount:10,
          sell_price: "299.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/jogger-casual-xam-nhat2_60.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/quan-ni-jogger-casual-xam.jpg",
          product_name: "Quần nỉ nam Jogger Casual co giãn - Xám nhạt",
          category_id:"ABC",
          amount:10,
          sell_price: "219.000đ",
          discount: "299.000đ",
          percent: "-27%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-navy-1.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-navy-2.jpg",
          product_name: "Áo thun thể thao dài tay nam Recycle Active - Xanh Navy",
          category_id:"ABC",
          amount:10,
          sell_price: "199.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-hoodie-den4_23.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-hoodie-den5_54.jpg",
          product_name: "Áo Hoodie nam Daily Wear (mũ trùm có dây rút) - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "349.000đ",
          discount: "399.000đ",
          percent: "-13%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-mu-daily-wear-xam-6_48.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-mu-daily-wear-xam-7.jpg",
          product_name: "Áo khoác nam có mũ Daily Wear - trượt nước, chống UV 99% - Xám",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-for-winter-xam-dam-2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-for-winter-xam-dam-6.jpg",
          product_name: "Áo khoác nỉ nam For Winter (có mũ trùm tiện lợi) - Xám đậm",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-xam-dam-2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-xam-dam-1_59.jpg",
          product_name: "Áo nỉ dài tay Lifewear - thoải mái khi mặc - Xám đậm",
          category_id:"ABC",
          amount:10,
          sell_price: "339.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "5",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/modal-ultra-warm-3_75.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-giu-nhiet-modal-mau-xam.jpg",
          product_name: "Áo giữ nhiệt nam Modal Ultra Warm - mặc là ấm, thoáng khí - Xám",
          category_id:"ABC",
          amount:10,
          sell_price: "289.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/kkasNNjac214.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/NNjac213.jpg",
          product_name: "Áo khoác gió thể thao HeiQ ViroBlock, chống UV & trượt nước - Xanh Navy",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/DSC04823.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/DSC04876.jpg",
          product_name: "Áo khoác gió thể thao đa năng cản gió và chống UV - Xanh rêu",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.7",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/soronada112.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/uxamsoro_copy.jpg",
          product_name: "Quần nam Daily Pants - sợi Sorona, nhuộm Cleandye - Xám xanh",
          category_id:"ABC",
          amount:10,
          sell_price: "299.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-xam-dam-1.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-xam-dam-2.jpg",
          product_name: "Áo thun thể thao dài tay nam Recycle Active - Xám đậm",
          category_id:"ABC",
          amount:10,
          sell_price: "199.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-for-winter-xam-nhat-2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-for-winter-xam-nhat-3.jpg",
          product_name: "Áo khoác nỉ nam For Winter (có mũ trùm tiện lợi) - Xám nhạt",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-xam-nhat-8.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-xam-nhat-99_2.jpg",
          product_name: "Áo nỉ dài tay Lifewear - thoải mái khi mặc - Xám nhạt",
          category_id:"ABC",
          amount:10,
          sell_price: "339.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "5",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/heiQ_reu_xam_xanh_2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/heiQ_reu_xam_xanh_1.jpg",
          product_name: "Áo khoác gió thể thao HeiQ ViroBlock, chống UV & trượt nước - Xám xanh",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/soronada132.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/udensoro_copy.jpg",
          product_name: "Quần nam Daily Pants - sợi Sorona, nhuộm Cleandye - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "299.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-xanh-reu-1.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-thun-the-thao-dai-tay-recycle-active-xanh-reu-2.jpg",
          product_name: "Áo thun thể thao dài tay nam Recycle Active - Xanh rêu",
          category_id:"ABC",
          amount:10,
          sell_price: "199.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-khoac-for-winter-xanh-reu-3_36.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-khoac-ni-for-winter-mau-reu.jpg",
          product_name: "Áo khoác nỉ nam For Winter (có mũ trùm tiện lợi) - Xanh rêu",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.9",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-xanh-reu-6_53.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/ao-ni-dai-tay-lifewear-xanh-reu-1_91.jpg",
          product_name: "Áo nỉ dài tay Lifewear - thoải mái khi mặc - Xanh rêu",
          category_id:"ABC",
          amount:10,
          sell_price: "339.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "5",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/heiQ_reu_new_2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/heiQ_reu_new_1.jpg",
          product_name: "Áo khoác gió thể thao HeiQ ViroBlock, chống UV & trượt nước - Xanh rêu",
          category_id:"ABC",
          amount:10,
          sell_price: "449.000đ",
          discount: "499.000đ",
          percent: "-10%",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/combo-ao-life-wear-quan-ni-jogger-casual-xam-2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/combo-ao-life-wear-quan-ni-jogger-casual-xam-2_4.jpg",
          product_name: "Bộ nỉ nam Casual - thoải mái khi mặc",
          category_id:"ABC",
          amount:10,
          sell_price: "539.000đ",
          discount: "638.000đ",
          percent: "-16%",
          product_id:'',
          stars: "0",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/1234231.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/November2021/BOY_7738-copy.jpg",
          product_name: "Quần thể thao Jogger co giãn - Xám nhạt",
          category_id:"ABC",
          amount:10,
          sell_price: "289.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.7",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/12342311.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/IMG_6966-copys.jpg",
          product_name: "Quần thể thao Jogger co giãn - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "289.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.7",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/combo-ao-dai-tay-recycle-active-den-quan-jogger-graphene-den-4_47.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/combo-ao-dai-tay-recycle-active-xanh-reu-quan-jogger-graphene-den-4_7.jpg",
          product_name: "Set đồ thể thao Warm Winter - Năng động thoải mái",
          category_id:"ABC",
          amount:10,
          sell_price: "399.000đ",
          discount: "538.000đ",
          percent: "-26%",
          product_id:'',
          stars: "0",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/graphenee.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/May2022/graphene_thumb.jpg",
          product_name: "Quần Jogger thể thao co giãn Graphene - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "339.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.7",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/Ghi_truoc.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/March2022/deggraphen-xam_copy.jpg",
          product_name: "Quần Jogger thể thao co giãn Graphene - Xám",
          category_id:"ABC",
          amount:10,
          sell_price: "339.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.7",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/anh-2D-ao-thun-dai-tay-cotton-compact-xam-dam-8_13.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/anh-chi-tiet-ao-thun-dai-tay-cotton-compact-xam-dam-3_30.jpg",
          product_name: "Áo thun nam dài tay Cotton Compact V2 - Xám đậm",
          category_id:"ABC",
          amount:10,
          sell_price: "269.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-xam2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-xam3.jpg",
          product_name: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          category_id:"ABC",
          amount:10,
          sell_price: "269.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-reu2_70.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-reu4.jpg",
          product_name: "Áo thun nam dài tay Cotton Compact V2 - Rêu",
          category_id:"ABC",
          amount:10,
          sell_price: "269.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-navy2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-navy3.jpg",
          product_name: "Áo thun nam dài tay Cotton Compact V2 - Xanh Navy",
          category_id:"ABC",
          amount:10,
          sell_price: "269.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-trang3.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-trang2.jpg",
          product_name: "Áo thun nam dài tay Cotton Compact V2 - Trắng",
          category_id:"ABC",
          amount:10,
          sell_price: "269.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.8",
        },
        {
          illustration : "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-den2.jpg",
          illustration2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/ao-dai-tay-compact-v2-den3.jpg",
          product_name: "Áo thun nam dài tay Cotton Compact V2 - Đen",
          category_id:"ABC",
          amount:10,
          sell_price: "269.000đ",
          discount: "",
          percent: "",
          product_id:'',
          stars: "4.8",
        },
      
      ],
      PANT: [
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/kaki-excool-xam-den.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/xamdenDSC00016.jpg",
          name: "Quần dài Kaki Excool co giãn - Xám đen",
          price: "419.000đ",  
          price_import:"300.000đ",
          manufacturer:"CocaCOla",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "499.000đ",
          percent: "-16%",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/11-181.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/soronanavyu_32.jpg",
          name: "Quần nam Daily Pants - sợi Sorona, nhuộm Cleandye - Xanh Navy",
          price: "299.000đ",
          price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/September2022/jogger-casual-xam-nhat2_60.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/quan-ni-jogger-casual-xam.jpg",
          name: "Quần nỉ nam Jogger Casual co giãn - Xám nhạt",
          price: "219.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "299.000đ",
          percent: "-27%",
          stars: "4.9",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/1DSC06643-copy-2.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/32-0.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit - Xanh nhạt",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "4.8",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/1234231.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/November2021/BOY_7738-copy.jpg",
          name: "Quần thể thao Jogger co giãn - Xám nhạt",
          price: "289.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/graphenee.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/May2022/graphene_thumb.jpg",
          name: "Quần Jogger thể thao co giãn Graphene - Đen",
          price: "339.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xanh_nhat_s3_1.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xanh_nhat_s3_2.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit S3 - Xanh nhạt",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "4.9",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/Jeans_moi_dam_1.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/Jeans_moi_dam_2.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit S2 - Xanh đậm",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/kaki-excool-begie.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/March2022/1-copy-4_23.jpg",
          name: "Quần dài Kaki Excool co giãn - Beige",
          price: "419.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "499.000đ",
          percent: "-16%",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/soronada112.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/uxamsoro_copy.jpg",
          name: "Quần nam Daily Pants - sợi Sorona, nhuộm Cleandye - Xám xanh",
          price: "299.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/1DSC06626-copy.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/33-0.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit - Xanh garment",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "4.8",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/12342311.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/IMG_6966-copys.jpg",
          name: "Quần thể thao Jogger co giãn - Đen",
          price: "289.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/Ghi_truoc.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/March2022/deggraphen-xam_copy.jpg",
          name: "Quần Jogger thể thao co giãn Graphene - Xám",
          price: "339.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/xanhdammm_27.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/October2022/quan-jean-slimfit-s3_(1).jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit S3 - Xanh đậm",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "4.9",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/Jeans_moi_nhat_2.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/Jeans_moi_nhat_4.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit S2 - Xanh nhạt",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/kaki-excool-xanh-dam.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/June2022/1DSC00016_34.jpg",
          name: "Quần dài Kaki Excool co giãn - Xanh đậm",
          price: "419.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "499.000đ",
          percent: "-16%",
          stars: "4.7",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/soronada132.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/February2022/udensoro_copy.jpg",
          name: "Quần nam Daily Pants - sợi Sorona, nhuộm Cleandye - Đen",
          price: "299.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "",
          percent: "",
          stars: "",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/1DSC06684-copy.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/April2022/31-0.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit - Xanh đậm",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "4.8",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/xanhsanggg_74.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/xanh-sang_1.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit S2 - Xanh sáng",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "",
        },
        {
          img1: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/garmetnnt_39.jpg",
          img2: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/July2022/gament_2.jpg",
          name: "Quần Jeans Clean Denim dáng Slimfit S2 - Xanh garment",
          price: "399.000đ",
           price_import:"300.000đ",
          manufacturer:"CocaCOla",
          discount: "599.000đ",
          percent: "-33%",
          stars: "",
        },
      ],
      
    },
    type: "ALL",
    fuel: "ALL",
  },
  reducers: {
    loginStart: (state) => {
      state.login.isFetching = true;
    },
    loginSuccess: (state, action) => {
      state.login.isFetching = false;
      state.login.currentUser = action.payload;
      state.login.isLogin = true;
    },
    loginFalse: (state) => {
      state.login.isFetching = false;
      state.login.error = true;
    },
    registerStart: (state) => {
      state.register.isFetching = true;
    },
    registerSuccess: (state) => {
      state.register.isFetching = false;
      state.register.success = true;
    },
    registerFalse: (state) => {
      state.register.isFetching = false;
      state.register.error = true;
      state.register.success = false;
    },
    filter: (state, action) => {
      state.type = action.payload.type_;
      state.fuel = action.payload.fuel;
    },
    addCart:(state,action)=>{
      state.login.currentUser = action.payload;
    },
    logout: (state) => {
      state.login.isLogin = false;
      state.login.currentUser = null;
    },
    commentSuccess: (state) => {
      state.comment.success = true;
    },
    commentError: (state) => {
      state.comment.error = true;
    },
    updateSuccess: (state) => {
      state.login.uploadAvt = true;
    },
  },
});

export const {
  loginStart,
  updateSuccess,
  commentSuccess,
  commentError,
  logout,
  filter,
  loginSuccess,
  loginFalse,
  registerFalse,
  registerSuccess,
  registerStart,
  loginInit,
  addCart,
} = authSlice.actions;
export default authSlice.reducer;
